server:
  port: 8085

spring:
  application:
    name: Tweet-Service
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:postgresql://localhost:5432/tweetDB2
    username: user-name
    password: strong-password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



