services:
  postgres:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    networks:
      - postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    networks:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  zipkin-slim:
    image: openzipkin/zipkin-slim
    ports:
      - "9411:9411"

networks:
  postgres:
    driver: bridge
volumes:
  local_pgdata:
  pgadmin-data:



